# apiVersion: v1
# data:
#   mapRoles: |
#     - rolearn: arn:aws:iam::677673473487:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-WavcE2WgELwT
#       groups:
#       - system:bootstrappers
#       - system:nodes
#       username: system:node:{{EC2PrivateDNSName}}
#   mapUsers: |
#     - userarn: arn:aws:iam::677673473487:user/mahi
#       username: mahi
#       groups:
#       - roboshop-trainee
# kind: ConfigMap
# metadata:
#   creationTimestamp: "2026-09-05T06:47:33Z"
#   name: aws-auth
#   namespace: kube-system
#   uid: 91b8f891-d58a-4d6b-9b59-59bf014995d4

apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::677673473487:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-MRj9ANh78vb6
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::677673473487:user/mahi
      username: mahi
      groups:
      - roboshop-trainee  
    - userarn: arn:aws:iam::677673473487:user/ramesh
      username: ramesh
      groups:
      - roboshop-admin 
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-07T17:16:08Z"
  name: aws-auth
  namespace: kube-system
  uid: 947ed999-e36b-4f76-8d79-137b7b58414f

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: aws-auth
#   namespace: kube-system

# data:
#   mapRoles: |
#     - rolearn: arn:aws:iam::677673473487:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-WavcE2WgELwT
#       groups:
#       - system:bootstrappers
#       - system:nodes
#       username: system:node:{{EC2PrivateDNSName}}

#   mapUsers: |
#     - userarn: arn:aws:iam::677673473487:user/mahi
#       username: mahi
#       groups:
#       - mahi-group