apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::677673473487:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-WavcE2WgELwT
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::677673473487:user/mahi
      username: mahi
      groups:
      - mahi-group
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-05T06:47:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1218"
  uid: 91b8f891-d58a-4d6b-9b59-59bf014995d4
